server:
  port: 8081
spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
application:
  secretKey: hfgry463hf746hf573ydh475fhy5739hfgry463hf746hf573ydh475fhy5739hfgry463hf746hf573ydh475fhy5739
  tokenExpiry: 86400000



